### ISSUE TITLE
[FORMATTING/LAYOUT]

### ISSUE THREAD

**Issue by IHNTABIAB** [AnonymousPlanet/thgtoa#18] opened 2021-02-15 18:50 UTC
### Formatting/Layout Issue: PDF's appear to be raster not vector images.

The two non-password protected PDFs (for version 0.7.4) appear much blurrier than 0.7.3 version. The quality deteriorates as I zoom in. This is not an issue on the password protected PDF, thankfully. Not a huge deal, but though you should know how its showing up for me since the previous version did not have this issue.

Also, on your website, it still says that you are on version 0.7.3

**Comment by AnonymousPlanet** [comment] 2021-02-15 21:46
I did notice it and I'll fix it ASAP ... there are also referencing issues in the new ones.

**Comment by AnonymousPlanet** [comment] 2021-02-16 16:33
Could you let me know if the issue is now fixed on your side?

**Comment by AnonymousPlanet** [comment] 2021-02-17 11:31
I'll consider this as resolved since it looks fine to me :)

**Closed by AnonymousPlanet** 2021-02-17 11:31 UTC
Labels: Formating/Layout

**Comment by IHNTABIAB** [comment] 2021-02-17 14:42
Sorry, just saw this. Yep it looks good to me.
